#!/bin/sh
USAGE="Usage: $(basename "$0") [options]

Options:
-y      Assume the user answered YES on all confirmation requests
-h      Show this usage help
"

BASE="$(dirname "$(readlink -f "$0")")"
. "$BASE/lib.sh"

# Parse arguments
O_YES=0
while getopts hy opt; do
    case "$opt" in
        y)
            O_YES=1
            ;;
        h)
            echo "$USAGE"
            exit
            ;;
        \?)
            echo "$USAGE"
            exit 1
            ;;
    esac
done
shift $(($OPTIND - 1))

D="$PWD"
cd "$BASE"
git submodule update --init --recursive
cd "$D" && unset D

# Install basic programs
if askYn "Install basic programs?" $O_YES
then
    info "Installing basic programs..."
    sudo apt install -y software-properties-common
    sudo add-apt-repository -y ppa:jonathonf/vim
    sudo apt update
    sudo apt install -y \
        cmake \
        ctags \
        htop \
        most \
        parallel \
        pv \
        ranger \
        silversearcher-ag \
        stow \
        tmux \
        vim \
        zsh \
        || die "installing programs"
    info "done."
fi

# Install GUI programs
if askYn "Install GUI programs?" $O_YES
then
    info "Installing GUI programs..."
    sudo apt install -y \
        rxvt-unicode-256color \
        vim-gtk \
        || die "installing programs"
    info "done."
fi

info "Linking dotfiles in $HOME..."
# Check for stow
if ! which stow >/dev/null; then
    if askYn "Stow not found. Do you want to install it to proceed?" $O_YES
    then
        sudo apt install -yq stow || die "installing stow"
    else
        die "can't link dotfiles without stow"
    fi
fi
# Link dotfiles
cd "$BASE"
find -maxdepth 1 -type d -not -name '.*' -printf "%P\n" | while read -r d; do
    restow "$d" || die "restowing $d"
done || die "restowing"
info "done."

info "Initializing dotfiles git submodules..."
cd "$BASE" # just in case
git submodule update --init
info "done."

info "Installing vim plugins..."
vim +PluginInstall +qall || die "installing vim plugins"
info "done."

