#!/bin/sh
USAGE="Usage: $(basename "$0") [options]

Options:
-y      Assume the user answered YES on all confirmation requests
-h      Show this usage help
"

BASE="$(dirname "$(readlink -f "$0")")"
. "$BASE/lib.sh"

# Parse arguments
O_YES=0
while getopts hy opt; do
    case "$opt" in
        y)
            O_YES=1
            ;;
        h)
            echo "$USAGE"
            exit
            ;;
        \?)
            echo "$USAGE"
            exit 1
            ;;
    esac
done
shift $(($OPTIND - 1))

info "Initializing dotfiles git submodules..."
cd "$BASE"
git submodule update --init --recursive
info "done."

# Install basic programs
if askYn "Install basic programs?" $O_YES
then
    info "Installing basic programs..."

    if awk "BEGIN { exit 1 - ($(lsb_release -sr) < 17.04) }"; then
        # to get vim 8 from PPA
        sudo apt install -yq software-properties-common
        sudo add-apt-repository -y ppa:jonathonf/vim
    fi

    sudo apt update

    sudo apt install -yq \
        ctags \
        curl \
        htop \
        most \
        parallel \
        pv \
        ranger \
        silversearcher-ag \
        stow \
        tmux \
        vim \
        zsh \
        zip unzip \
        || die "installing programs"

    info "done."
fi

info "Linking dotfiles in $HOME..."
# Check for stow
if ! which stow >/dev/null; then
    if askYn "Stow not found. Do you want to install it to proceed?" $O_YES
    then
        sudo apt install -yq stow || die "installing stow"
    else
        die "can't link dotfiles without stow"
    fi
fi
# Link dotfiles
cd "$BASE/home"
find -maxdepth 1 -type d -not -name '.*' -printf "%P\n" | while read -r d; do
    restow "$d" || die "restowing $d"
done || die "restowing"
info "done."

info "Installing vim plugins..."
vim +PluginInstall +qall || die "installing vim plugins"
info "done."

